"""create initial ticketpilot tables

Revision ID: 3b886ca58548
Revises: 
Create Date: 2026-09-17 19:22:21.356818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b886ca58548'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'RESOLVED', 'ESCALATED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('final_answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('audit',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('drafts',
    sa.Column('generated_answer', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=False),
    sa.Column('validation_result', sa.String(), nullable=True),
    sa.Column('model_metadata', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drafts')
    op.drop_table('audit')
    op.drop_table('tickets')
    # ### end Alembic commands ###
