"""add reviewer identity and answer

Revision ID: 46e8219f5d85
Revises: e4945e8ad0a7
Create Date: 2026-09-27 19:36:11.709062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e8219f5d85'
down_revision: Union[str, Sequence[str], None] = 'e4945e8ad0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewer_identity', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('reviewer_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewer_answer')
    op.drop_column('reviews', 'reviewer_identity')
    # ### end Alembic commands ###
