"""add reviews table

Revision ID: bf0dd3917422
Revises: 3251ba6a5b22
Create Date: 2026-09-27 16:41:04.256492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0dd3917422'
down_revision: Union[str, Sequence[str], None] = '3251ba6a5b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('agent_decision', sa.Enum('ANSWER', 'ESCALATE', name='agentdecision'), nullable=False),
    sa.Column('agent_reason', sa.String(), nullable=False),
    sa.Column('reviewer_action', sa.Enum('APPROVE', 'EDIT', 'ESCALATE', name='revieweraction'), nullable=True),
    sa.Column('reviewer_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
